apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-sq7k
  namespace: jhutar-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:420237e307ef1c8851d08dc6faecd37ebc37110fef1a24ccd846b581784d156c
        name: my-python
        resources: {}
status: {}
